[server]
maxUploadSize = 10
enableXsrfProtection = true
enableCORS = false

[logger]
level = "error"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
base="light"
